### PR TITLE
feat(claudeup): upgrade claude to use 2.1

### LINKED ISSUE #139: (QA/Summarization): Update model to Anthropic Claude v2.1
### Describe the feature

Current implementation uses Anthropic Claude v2.0, request to update to Anthropic Claude v2.1

### Use Case

https://www.anthropic.com/index/claude-2-1 
Longer context windows, reduced hallucinations

### Proposed Solution

_No response_

### Other Information

_No response_

### Acknowledgements

- [ ] I may be able to implement this feature request
- [ ] This feature might incur a breaking change

### PR DESCRIPTION
**Pull request by oconpa**
Fixes #139 

---
By submitting this pull request, I confirm that you can use, modify, copy, and redistribute this contribution, under the terms of the project license.

### CODE REVIEW

**Review by scottschreckengaust — DISMISSED** [review]

**Comment by krokoko** [comment]
Hi @oconpa, thanks ! I just edited your comment to add a link to the related ticket in the backlog.

One thing missing is the update of the context window size in the lambda function (https://github.com/awslabs/generative-ai-cdk-constructs/blob/main/lambda/aws-qa-appsync-opensearch/question_answering/src/llms/text_generation_llm_selector.py#L92C5-L92C5) to 200k

**Review by krokoko — CHANGES_REQUESTED** [review]
https://github.com/awslabs/generative-ai-cdk-constructs/blob/main/lambda/aws-qa-appsync-opensearch/question_answering/src/llms/text_generation_llm_selector.py#L92C5-L92C5 -> update to 200k 

Also, did you run a test to verify that the workflow works as expected ? just to make sure there is no need to update the payload format of any supporting library version

**Comment by krokoko** [comment]
Hi @oconpa , I see you fixed the token limit issue, thanks ! Were you able to test it by any chance ? So we can close this PR

**Comment by oconpa** [comment]
> Hi @oconpa , I see you fixed the token limit issue, thanks ! Were you able to test it by any chance ? So we can close this PR

Can we merge this PR first (https://github.com/awslabs/generative-ai-cdk-constructs/pull/198#issuecomment-1906735746), then this one?

**Comment by krokoko** [comment]
> > Hi @oconpa , I see you fixed the token limit issue, thanks ! Were you able to test it by any chance ? So we can close this PR
> 
> Can we merge this PR first (#205), then this one?

Done, thanks for your contribution ! :)

**Comment by oconpa** [comment]
Tested

**Review by scottschreckengaust — APPROVED** [review]
LGTM

**Review by dineshSajwan — APPROVED** [review]
LGTM

**Pull request merged**
