### PR TITLE
fix: embedding_job is failing to generate embeddings

### PR DESCRIPTION
**Pull request by saikatak**
When trying to ingest a file Step function state machine is failing at "generate embeddings from processed documents and store them" with the error : "process_shard() missing 1 required positional argument: model_id" updated code to pass model_id to process_shard() method
image

Fixes #
Issue - process_shard() missing 1 required positional argument: model_id
---
By submitting this pull request, I confirm that you can use, modify, copy, and redistribute this contribution, under the terms of the project license.

### CODE REVIEW

**Review by krokoko — APPROVED** [review]

**Review by dineshSajwan — APPROVED** [review]

**Comment by saikatak** [comment]
@krokoko / @dineshSajwan  in which version of cdk gen ai construct , I will be getting this fix?

**Comment by krokoko** [comment]
Hi @saikatak , this was merged a while ago, if you take the latest version of the constructs the fix will be in. If you want the first version of the constructs published with the fix, it would be https://github.com/awslabs/generative-ai-cdk-constructs/releases/tag/v0.1.136

**Comment by saikatak** [comment]
@krokoko  thanks for the info . But with the latest versions >= 0.1.136 , I am facing below issue for embedding lambda:
[ERROR] AttributeError: 'NoneType' object has no attribute 'append_keys'
Traceback (most recent call last):
  File "/var/lang/lib/python3.11/site-packages/aws_lambda_powertools/logging/logger.py", line 455, in decorate
    self.append_keys(cold_start=cold_start, **lambda_context.__dict__)
  File "/var/lang/lib/python3.11/site-packages/aws_lambda_powertools/logging/logger.py", line 603, in append_keys
    self.registered_formatter.append_keys(**additional_keys)

**Comment by krokoko** [comment]
Hi @saikatak , could you please open a new issue and provide the specific parameters you provide to the construct to reproduce this ? Thank you

**Pull request merged**
