### PR TITLE
chore(patterns): Add Python snippets to constructs' patterns README files

### LINKED ISSUE #141: (Constructs README): add Python code snippets
### Describe the issue

Each construct README provides a code snippet for Typescript (minimum deployable pattern definition), however there is no code snippet for Python

### Links

https://github.com/awslabs/generative-ai-cdk-constructs/tree/main/src/patterns/gen-ai -> every README

### PR DESCRIPTION
**Pull request by martinezedgar**
Closes #141
@krokoko

Python snippets were tested by correctly synthetizing them. (Pending HuggingFace and JumpStart)

---
By submitting this pull request, I confirm that you can use, modify, copy, and redistribute this contribution, under the terms of the project license.

### CODE REVIEW

**Review by scottschreckengaust — CHANGES_REQUESTED** [review]
Please confirm python examples have successfully tested.

**Comment by martinezedgar** [comment]
Hi @scottschreckengaust, sure I'll be testing all the python examples.

**Comment by martinezedgar** [comment]
Hi @krokoko, sorry for the delay in getting this done, I am having some new issues with the Python snippets in the latest release (0.1.46) with `LangCommonLayer` and `JumpStartSageMakerEndpoint`:

**LangCommonLayer**

```python
lambda_architecture = lambda_.Architecture.ARM_64
lambda_runtime = lambda_.Runtime.PYTHON_3_10

# This is one way of getting a lambda powertools layer
powertools_arn = (
    f'arn:aws:lambda:{Aws.REGION}:017000801446:'
    'layer:AWSLambdaPowertoolsPythonV2-Arm64:42'
)

if lambda_architecture == lambda_.Architecture.X86_64:
    powertools_arn = (
        f'arn:aws:lambda:{Aws.REGION}:017000801446:'
        'layer:AWSLambdaPowertoolsPythonV2:42'
    )

lambda_deps_layer = LangchainCommonDepsLayer(
    self,
    'lambdagenaidepslayer',
    runtime=lambda_runtime,
    architecture=lambda_architecture,
    auto_upgrade=True,
)

lambda_common_layer = LangchainCommonLayer(
    self,
    'lambdagenaicommonlayer',
    compatible_runtimes=[lambda_runtime],
    compatible_architectures=[lambda_architecture],
)
```

When running `cdk synth` this is the error I get for `LangChainCommonLayer`:

```bash
jsii.errors.JavaScriptError: 
  Error: Cannot find asset at /var/folders/kv/rk20vrnn0xv4psrsn47ffq8h0000gn/T/jsii-kernel-oDF8zb/node_modules/@cdklabs/generative-ai-cdk-constructs/layers/model-adapter-layer
      at new AssetStaging (/var/folders/kv/rk20vrnn0xv4psrsn47ffq8h0000gn/T/jsii-kernel-oDF8zb/node_modules/aws-cdk-lib/core/lib/asset-staging.js:1:2119)
      at new Asset (/var/folders/kv/rk20vrnn0xv4psrsn47ffq8h0000gn/T/jsii-kernel-oDF8zb/node_modules/aws-cdk-lib/aws-s3-assets/lib/asset.js:1:1080)
      at AssetCode.bind (/var/folders/kv/rk20vrnn0xv4psrsn47ffq8h0000gn/T/jsii-kernel-oDF8zb/node_modules/aws-cdk-lib/aws-lambda/lib/code.js:1:4881)
      at new LayerVersion (/var/folders/kv/rk20vrnn0xv4psrsn47ffq8h0000gn/T/jsii-kernel-oDF8zb/node_modules/aws-cdk-lib/aws-lambda/lib/layers.js:1:2277)
      at new LangchainCommonLayer (/var/folders/kv/rk20vrnn0xv4psrsn47ffq8h0000gn/T/jsii-kernel-oDF8zb/node_modules/@cdklabs/generative-ai-cdk-constructs/lib/patterns/gen-ai/aws-langchain-common-layer/index.js:68:23)
      at Kernel._Kernel_create (/private/var/folders/kv/rk20vrnn0xv4psrsn47ffq8h0000gn/T/tmphfvimgfk/lib/program.js:10108:25)
      at Kernel.create (/private/var/folders/kv/rk20vrnn0xv4psrsn47ffq8h0000gn/T/tmphfvimgfk/lib/program.js:9779:93)
      at KernelHost.processRequest (/private/var/folders/kv/rk20vrnn0xv4psrsn47ffq8h0000gn/T/tmphfvimgfk/lib/program.js:11696:36)
      at KernelHost.run (/private/var/folders/kv/rk20vrnn0xv4psrsn47ffq8h0000gn/T/tmphfvimgfk/lib/program.js:11656:22)
      at Immediate._onImmediate (/private/var/folders/kv/rk20vrnn0xv4psrsn47ffq8h0000gn/T/tmphfvimgfk/lib/program.js:11657:46)
```

**JumpStartSageMakerEndpoint**

```python
JumpStartSageMakerEndpoint(
    self,
    'LLAMA2',
    model=JumpStartModel.META_TEXTGENERATION_LLAMA_2_7_B_F_2_0_2,
    instance_type=SageMakerInstanceType.ML_G5_2_XLARGE,
    environment={
        'region': 'us-east-1',
    }
)
```

When running `cdk synth` this is the error I get for `JumpStartSageMakerEndpoint`:

```bash
jsii.errors.JavaScriptError: 
  Error: Region is unresolved. You should explicitly specify the region in the environment.
      at new JumpStartSageMakerEndpoint (/var/folders/kv/rk20vrnn0xv4psrsn47ffq8h0000gn/T/jsii-kernel-v756w6/node_modules/@cdklabs/generative-ai-cdk-constructs/lib/patterns/gen-ai/aws-model-deployment-sagemaker/jumpstart-sagemaker-endpoint.js:39:19)
      at Kernel._Kernel_create (/private/var/folders/kv/rk20vrnn0xv4psrsn47ffq8h0000gn/T/tmpeewi649f/lib/program.js:10108:25)
      at Kernel.create (/private/var/folders/kv/rk20vrnn0xv4psrsn47ffq8h0000gn/T/tmpeewi649f/lib/program.js:9779:93)
      at KernelHost.processRequest (/private/var/folders/kv/rk20vrnn0xv4psrsn47ffq8h0000gn/T/tmpeewi649f/lib/program.js:11696:36)
      at KernelHost.run (/private/var/folders/kv/rk20vrnn0xv4psrsn47ffq8h0000gn/T/tmpeewi649f/lib/program.js:11656:22)
      at Immediate._onImmediate (/private/var/folders/kv/rk20vrnn0xv4psrsn47ffq8h0000gn/T/tmpeewi649f/lib/program.js:11657:46)
      at process.processImmediate (node:internal/timers:476:21)
```

With this last issue I have tried to pass the region explicitly but I am still getting the error. Any help is much appreciated.

**Comment by krokoko** [comment]
Hi @martinezedgar no problem thanks ! Let me try and see if I can reproduce on the lambda layer
regarding the JumpStartSageMakerEndpoint, you need to indicate the region explicitly, for instance in your app.py : 
```
TestStack(app, "TestStack",
    env=cdk.Environment(account='123456789012', region='us-east-1'),
```

I tested with the following code snippets and it works as expected:

```
import cdklabs.generative_ai_cdk_constructs as genai

genai.HuggingFaceSageMakerEndpoint(
            self,
            id='Mistral',
            model_id= 'mistralai/Mistral-7B-Instruct-v0.1',
            instance_type= genai.SageMakerInstanceType.ML_G5_2_XLARGE,
            container= genai.DeepLearningContainerImage.HUGGINGFACE_PYTORCH_TGI_INFERENCE_2_0_1_TGI1_1_0_GPU_PY39_CU118_UBUNTU20_04,
            environment= {
                'SM_NUM_GPUS': '1',
                'MAX_INPUT_LENGTH': '2048',
                'MAX_TOTAL_TOKENS': '4096',
            },
        )
        genai.JumpStartSageMakerEndpoint(
            self,
            id='falcon',
            model=genai.JumpStartModel.HUGGINGFACE_LLM_FALCON_40_B_BF16_1_3_0,
            instance_type= genai.SageMakerInstanceType.ML_G5_12_XLARGE,
        )
```

**Comment by martinezedgar** [comment]
@krokoko You are right about the JumpStart, thank you!

**Comment by krokoko** [comment]
@martinezedgar there is indeed a regression in the latest version of the LangChainCommonLayer. I opened a PR (#227 ) which should address it and adds tests to prevent this from happening again. Once merged, you should be good to go ! Thank you again for reporting this !

**Comment by martinezedgar** [comment]
Perfect, I will push the latest changes.

**Review by krokoko — APPROVED** [review]

**Review by hvital — APPROVED** [review]

**Review by scottschreckengaust — APPROVED** [review]
Thank you for testing!

**Pull request merged**
