### PR TITLE
fix(doc): add notice when building on differing architectures

### LINKED ISSUE #541: (LangchainCommonDepsLayer): bundling
### Describe the bug

When instantiating the layer for the X_86 architecture, dependencies are not packaged correctly. Extensions modules are not compiled for the correct platform
When selecting X_86 as the layer compatible architecture:
image
While it should be:
image

### Expected Behavior

No runtime error

### Current Behavior

Runtime error

### Reproduction Steps

see the contract analysis sample

### Possible Solution

_No response_

### Additional Information/Context

_No response_

### CDK CLI Version

2.132.0

### Framework Version

_No response_

### Node.js Version

20

### OS

MacOs

### Language

Python

### Language Version

_No response_

### Region experiencing the issue

any

### Code modification

no

### Other information

_No response_

### Service quota

- [X] I have reviewed the service quotas for this construct

### PR DESCRIPTION
**Pull request by scottschreckengaust**
Fixes #541 

---
By submitting this pull request, I confirm that you can use, modify, copy, and redistribute this contribution, under the terms of the project license.

### CODE REVIEW

**Comment by scottschreckengaust** [comment]
Reformatted markdown too

**Comment by krokoko** [comment]
Could you please also remove this folder: https://github.com/awslabs/generative-ai-cdk-constructs/tree/main/layers/langchain-common-layer/python/genai_core as part of this PR ? It was a miss from a previous one :) Thanks !

**Comment by krokoko** [comment]
Closed by mistake

**Comment by scottschreckengaust** [comment]
> Could you please also remove this folder: https://github.com/awslabs/generative-ai-cdk-constructs/tree/main/layers/langchain-common-layer/python/genai_core as part of this PR ? It was a miss from a previous one :) Thanks !

done https://github.com/awslabs/generative-ai-cdk-constructs/commit/b96e47766f7ed223f00cf025447687e3fdeca193

**Review by krokoko — APPROVED** [review]

**Review by MichaelWalker-git — APPROVED** [review]

**Pull request merged**
