### PR TITLE
feat: Introduce Titan Text Embedding V2

### LINKED ISSUE #492: (bedrock): (Add TITAN_EMBED_TEXT_V2)
### Describe the feature

Titan Text Embeddings v2 is now available in the AWS management console.

image

### Use Case

When instantiating the KnowledgeBase class, set the embeddingsMode to TITAN_EMBED_TEXT_V2.

Currently, however, three patterns (1024, 512, and 256) can be specified as vectorDimensions, so it may be necessary to define each pattern as TITAN_EMBED_TEXT_V2_1024.

Or, assuming that arbitrary vectorDimensions can be specified in the future, can they be specified as parameters? We should also consider such a possibility.

image

### Proposed Solution

_No response_

### Other Information

_No response_

### Acknowledgements

- [x] I may be able to implement this feature request
- [ ] This feature might incur a breaking change

### PR DESCRIPTION
**Pull request by cagataycali**
Knowledge Bases for Bedrock supports `amazon.titan-embed-text-v2:0`.

Fixes #492 

---
By submitting this pull request, I confirm that you can use, modify, copy, and redistribute this contribution, under the terms of the project license.

### CODE REVIEW

**Comment by krokoko** [comment]
Hi @cagataycali thank you for this PR, did you try to deploy a KB with this model ?

**Comment by cagataycali** [comment]
Looks like while deploying CDK we're having a regexp error.

```
Properties validation failed for resource :: with message:
[#/KnowledgeBaseConfiguration/VectorKnowledgeBaseConfiguration/EmbeddingModelArn: string [arn:aws:bedrock:us-east-1::foundation-model/amazon.titan-embed-text-v2:0] does not match pattern ^arn:aws(-[^:]+)?:bedrock:[a-z0-9-]{1,20}:(([0-9]{12}:custom-model
/[a-z0-9-]{1,63}[.]{1}[a-z0-9-]{1,63}/[a-z0-9]{12})|(:foundation-model/[a-z0-9-]{1,63}[.]{1}[a-z0-9-]{1,63}))$]
```

**Review by krokoko — DISMISSED** [review]

**Comment by krokoko** [comment]
The underlying issue has been fixed, reopening this PR

**Review by krokoko — APPROVED** [review]

**Review by scottschreckengaust — CHANGES_REQUESTED** [review]
Waiting for confirmation to require a contributor statement

**Review by scottschreckengaust — APPROVED** [review]

**Pull request merged**
